In [6]:
import pandas as pd
import geopandas as gpd

In [ ]:
data = pd.read_csv('../data/movements-World-Bank---zonificacion-montevideo_3dias.csv')
data2 = pd.read_csv('../data/movements-World-Bank---zonificacion-montevideo-_7dias.csv')

In [89]:
zonas = gpd.read_file('../data/zonificacion-montevideo.gpkg').set_index('id_poligono')

In [49]:
(len(data[data['total_trips'] == '<10'])*10)/data[data['total_trips'] != '<10']['total_trips'].astype(float).sum()

np.float64(0.05359737988545061)

In [59]:
(len(data2[data2['total_trips'] == '<10'])*10)/data2[data2['total_trips'] != '<10']['total_trips'].astype(float).sum()

np.float64(0.0216168834691523)

In [71]:
(data2[data2['total_trips'] != '<10']['total_trips'].astype(float).sum()+(len(data2[data2['total_trips'] == '<10'])*10))/7

np.float64(6151311.972857143)

In [72]:
(data[data['total_trips'] != '<10']['total_trips'].astype(float).sum()+ (len(data[data['total_trips'] == '<10'])*10))/3

np.float64(6286837.206666667)

In [58]:
data2[data2['total_trips'] != '<10']['total_trips'].astype(float).sum()/7 - data[data['total_trips'] != '<10']['total_trips'].astype(float).sum()/3

np.float64(54132.861428571865)

In [67]:
data[(data['total_trips']=='<10')]

,start_date,end_date,destination,destination_name,origin,origin_name,total_trips
0,2025-10-01,2025-10-23,194,194,247,247,<10
1,2025-10-01,2025-10-23,194,194,248,248,<10
3,2025-10-01,2025-10-23,194,194,250,250,<10
4,2025-10-01,2025-10-23,194,194,251,251,<10
5,2025-10-01,2025-10-23,194,194,252,252,<10
...,...,...,...,...,...,...,...
196490,2025-10-01,2025-10-23,99,99,66,66,<10
196492,2025-10-01,2025-10-23,99,99,68,68,<10
196515,2025-10-01,2025-10-23,99,99,89,89,<10
196520,2025-10-01,2025-10-23,99,99,93,93,<10
196521,2025-10-01,2025-10-23,99,99,94,94,<10

In [69]:
zonas.loc[data[(data['origin']==247)&(data['total_trips']=='<10')].destination.to_list()].explore()

In [15]:
zonas

             tipo_zona                                           geometry
id_poligono
0                 Core  POLYGON ((560518.84 6154182.863, 560429.651 61...
1                 Core  POLYGON ((577159.412 6135221.747, 577083.505 6...
2                 Core  POLYGON ((577560.605 6135279.593, 577563.958 6...
3                 Core  POLYGON ((576481.842 6135919.188, 576468.236 6...
4                 Core  POLYGON ((576982.731 6136396.772, 576952.331 6...
...                ...                                                ...
551          Periferia  POLYGON ((521389.659 6187649.859, 521151.684 6...
552          Periferia  POLYGON ((663861.321 6178763.754, 663836.995 6...
553          Periferia  POLYGON ((722590.62 6146415.474, 722594.379 61...
554          Periferia  POLYGON ((659532.683 6136460.855, 659532.694 6...
555               Core  POLYGON ((570139.717 6140872.735, 570121.746 6...

[556 rows x 2 columns]

In [146]:
personas = pd.read_csv('../data/personas_ext_07_2026.csv', encoding = 'latin-1', dtype = {'ID_CENSO': 'str', 'DEPARTAMENTO': 'str', 'SEGMENTO': 'str', 'SECCION': 'str'})

/var/folders/c5/zm5_fc5x3g92v0z0h0c5mwfw0000gp/T/ipykernel_30245/3274058794.py:1: DtypeWarning: Columns (0: BARRIO85, 1: ESTRATO) have mixed types. Specify dtype option on import or set low_memory=False.
  personas = pd.read_csv('../data/personas_ext_07_2026.csv', encoding = 'latin-1', dtype = {'ID_CENSO': 'str', 'DEPARTAMENTO': 'str', 'SEGMENTO': 'str', 'SECCION': 'str'})

In [147]:
personas['CODSEG'] = personas['DEPARTAMENTO'] + personas['SECCION'] + personas['SEGMENTO']

/var/folders/c5/zm5_fc5x3g92v0z0h0c5mwfw0000gp/T/ipykernel_30245/1418748126.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  personas['CODSEG'] = personas['DEPARTAMENTO'] + personas['SECCION'] + personas['SEGMENTO']

In [148]:
zonas_censo = gpd.read_file('../data/sg_23_pg.gpkg')
zonas_censo = zonas_censo.to_crs(zonas.crs)

In [149]:
merge = gpd.sjoin(zonas, zonas_censo, predicate = 'intersects', how = 'left')

In [150]:
merge.CODSEG

id_poligono
0      0109042
0      0109041
0      0109039
0      0109040
0      0305116
        ...
555    0120007
555    0120011
555    0120010
555    0120014
555    0120013
Name: CODSEG, Length: 8219, dtype: str

In [151]:
len(zonas), len(zonas_censo), len(merge)

(556, 4538, 8219)

In [153]:
len(merge['index_right'].unique())

3195

In [154]:
personas[(personas['PERNA01']>=18)&(personas['CODSEG'].isin(list(merge['CODSEG'].unique())))].W.sum()

np.float64(2116519.0067791278)

In [132]:
personas.W.sum()

np.float64(3499451.0007258058)

In [136]:
len(personas)

3151118

In [142]:
personas[personas['ID_CENSO'].isin(list(merge['CODSEG'].unique()))]

,ID_CENSO,DIRECCION_ID,DEPARTAMENTO,LOCALIDAD,LOCALIDAD_AGRUP,SECCION,SECCION_AGRUP,SEGMENTO,SEGMENTO_AGRUP,VIVID,...,PERFM01,PERFM01_2,PERFM01_3,PERFM02,PERFM04_1,PERFM05,ID_UPM,W,ESTRATO,TR
3226,1401113,13005140.0,13,20,0,1,0,4,0,1.0,...,5,1,4,2,9999,9999,554413.0,1.027482,1301004,0.930258
7290,1907006,3064021.0,3,724,0,8,0,213,0,1.0,...,7777,7777,7777,7777,7777,7777,649613.0,0.997080,0308213,0.953544
7517,1006209,3236083.0,3,627,0,17,0,270,0,1.0,...,0,7777,7777,7777,7777,7777,380474.0,1.070150,0317270,0.929538
9594,1002013,1313080.0,1,20,0,10,0,64,0,1.0,...,7777,7777,7777,7777,7777,7777,1012836.0,1.015105,0110064,0.990062
10128,1006104,1172355.0,1,20,0,13,0,18,0,1.0,...,1,1,0,1,1995,1995,732026.0,1.057440,0113018,0.915153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3140898,1602209,3229695.0,3,953,0,37,0,484,0,1.0,...,2,0,2,2,2015,2008,846511.0,1.014820,0337484,0.936708
3143946,1605006,1244563.0,1,20,0,10,0,146,0,1.0,...,0,7777,7777,7777,7777,7777,1213784.0,1.035535,0110146,0.993077
3146163,1601011,3275897.0,3,343,0,4,0,338,0,1.0,...,7777,7777,7777,7777,7777,7777,446720.0,0.986330,0304338,0.852632
3147909,1001024,10067536.0,10,20,0,1,0,633,0,1.0,...,7777,7777,7777,7777,7777,7777,826329.0,1.107587,1001633,0.896442
3149982,1005104,1130534.0,1,20,0,10,0,338,0,1.0,...,3,1,2,2,1958,1952,927734.0,1.007892,0110338,0.965616